'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import AuthGuard from '@/components/AuthGuard';
import {api} from '@/lib/api';

type Product={id:string|number;slug?:string;name:string;price?:number;mrp?:number;image?:string};
function WishlistContent(){const [items,setItems]=useState<Product[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{api<any>('/wishlist').then(r=>setItems(r.data?.items||r.items||r.data||[])).catch(e=>setError(e instanceof Error?e.message:'Unable to load wishlist')).finally(()=>setLoading(false))},[]);async function remove(id:string|number){try{await api(`/wishlist/${id}`,{method:'DELETE'});setItems(a=>a.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:'Unable to remove item')}}return <main className="catalogPage"><div className="sectionHead"><div><span className="eyebrow">PRIYASA / SAVED</span><h1>Wishlist</h1></div><Link className="textLink" href="/shop">Continue shopping →</Link></div>{loading?<p className="muted">Loading your wishlist…</p>:error&&!items.length?<div className="emptyState"><h2>We couldn't load your wishlist</h2><p>{error}</p><button className="button" onClick={()=>location.reload()}>Retry</button></div>:!items.length?<div className="emptyState"><h2>Your wishlist is empty</h2><p>Save pieces you love and come back to them anytime.</p><Link className="button" href="/shop">Discover styles</Link></div>:<div className="productGrid">{items.map(p=><article className="productCard" key={String(p.id)}><Link href={`/product/${p.slug||p.id}`}><div className="productImage">{p.image&&<img src={p.image} alt={p.name}/>}</div><div className="productMeta"><strong>{p.name}</strong><b>₹{Number(p.price||0).toLocaleString('en-IN')}</b>{p.mrp&&p.mrp>Number(p.price||0)&&<del>₹{Number(p.mrp).toLocaleString('en-IN')}</del>}</div></Link><button className="textButton" onClick={()=>remove(p.id)}>Remove</button></article>)}</div>}</main>}
export default function Wishlist(){return <AuthGuard><WishlistContent/></AuthGuard>}
