'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
function money(v:any){return `₹${Number(v||0).toLocaleString('en-IN')}`}
function label(v:any){return String(v||'pending').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
export default function ReturnDetail(){const {id}=useParams<{id:string}>();const [item,setItem]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api<any>(`/storefront/returns/${encodeURIComponent(id)}`);setItem(r?.data?.return??r?.data??r?.return??r)}catch(e){setError(e instanceof Error?e.message:'Unable to load this return.')}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);if(loading)return <main className="accountPage"><div className="emptyState"><h2>Loading return…</h2></div></main>;if(error)return <main className="accountPage"><div className="emptyState"><h1>Return unavailable</h1><p>{error}</p><button className="button" onClick={()=>void load()}>Retry</button></div></main>;if(!item)return null;const order=item.order_number||item.order_id;const lines=item.items||item.line_items||[];return <main className="accountPage"><div className="sectionHead"><div><span className="eyebrow">PRIYASA / RETURN</span><h1>Return #{item.id||id}</h1><p className="muted">{order?`Order #${order}`:'Return request'}</p></div><Link className="textLink" href="/returns">← All returns</Link></div><section className="checkoutCard"><div className="orderStatus"><span>Status</span><strong>{label(item.status)}</strong></div>{item.reason&&<p><strong>Reason:</strong> {item.reason}</p>}{item.refund_amount!=null&&<p><strong>Refund amount:</strong> {money(item.refund_amount)}</p>}{item.refund_status&&<p><strong>Refund:</strong> {label(item.refund_status)}</p>}</section>{lines.length>0&&<section className="checkoutCard"><span className="eyebrow">RETURN ITEMS</span>{lines.map((l:any,i:number)=><div className="orderLine" key={String(l.id||l.order_item_id||i)}><div><strong>{l.product_name||l.name||l.product?.name||'PRIYASA product'}</strong><small>Qty {l.quantity||1}{l.variant_label?` · ${l.variant_label}`:''}</small></div><b>{l.amount!=null?money(l.amount):''}</b></div>)}</section>}<div className="emptyState"><p>Your return status and refund outcome are controlled by PRIYASA Core. This page does not assume a refund is complete until Core reports it.</p></div></main>}
