'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import AuthGuard from '@/components/AuthGuard';import {api} from '@/lib/api';
const empty={name:'',phone:'',address_line1:'',address_line2:'',city:'',state:'',postal_code:'',type:'home'};
function AddressesContent(){const [items,setItems]=useState<any[]>([]);const [form,setForm]=useState<any>(empty);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){try{const r=await api<any>('/addresses');setItems(r.data?.addresses||r.addresses||r.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load addresses')}}useEffect(()=>{load()},[]);
function change(k:string,v:string){setForm((x:any)=>({...x,[k]:v}))}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<any>('/addresses',{method:'POST',body:JSON.stringify(form)});const a=r.data?.address||r.address||r.data;if(a)setItems(x=>[...x,a]);else await load();setForm(empty);setOpen(false)}catch(e){setError(e instanceof Error?e.message:'Unable to save address')}finally{setBusy(false)}}
async function remove(id:any){if(!confirm('Remove this address?'))return;try{await api(`/addresses/${id}`,{method:'DELETE'});setItems(x=>x.filter(a=>a.id!==id))}catch(e){setError(e instanceof Error?e.message:'Unable to remove address')}}
return <main className="accountPage"><div className="sectionHead"><div><span className="eyebrow">PRIYASA / ACCOUNT</span><h1>Delivery addresses</h1></div><Link className="textLink" href="/checkout">Back to checkout →</Link></div>{error&&<div className="formError" role="alert">{error}</div>}<button className="button" onClick={()=>setOpen(true)}>+ Add new address</button>{open&&<form className="addressForm" onSubmit={save}><h2>Add delivery address</h2>{(['name','phone','address_line1','address_line2','city','state','postal_code'] as const).map(k=><label key={k}>{k==='address_line1'?'Address line 1':k==='address_line2'?'Address line 2':k==='postal_code'?'PIN code':k[0].toUpperCase()+k.slice(1)}<input required={k!=='address_line2'} value={form[k]} onChange={e=>change(k,e.target.value)} inputMode={k==='phone'||k==='postal_code'?'numeric':undefined}/></label>)}<div><button className="button" disabled={busy}>{busy?'Saving…':'Save address'}</button><button type="button" className="textButton" onClick={()=>setOpen(false)}>Cancel</button></div></form>}<div className="addressList">{items.map(a=><article className="checkoutCard" key={a.id}><strong>{a.name}</strong><p>{a.address_line1||a.line1}{a.address_line2&&`, ${a.address_line2}`}</p><p>{a.city}, {a.state} {a.postal_code||a.pincode}</p>{a.phone&&<small>{a.phone}</small>}<button className="textButton" onClick={()=>remove(a.id)}>Remove</button></article>)}</div>{!items.length&&!open&&<div className="emptyState"><h2>No saved addresses</h2><p>Add an address to make checkout faster.</p></div>}</main>}
export default function Addresses(){return <AuthGuard><AddressesContent/></AuthGuard>}
