'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';

function unwrap(r:any){const d=r?.data??r??{};return {shipment:d.shipment??null,tracking:d.tracking??d.tracking_data??null};}
function text(v:any){return String(v??'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
export default function Tracking(){const {id}=useParams<{id:string}>();const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{setData(unwrap(await api<any>(`/storefront/orders/${encodeURIComponent(id)}/tracking`)));}catch(e){setError(e instanceof Error?e.message:'Unable to load tracking.');}finally{setLoading(false);}},[id]);useEffect(()=>{void load()},[load]);if(loading)return <main className="accountPage"><div className="emptyState"><h2>Loading tracking…</h2></div></main>;if(error)return <main className="accountPage"><div className="emptyState"><h1>Tracking unavailable</h1><p>{error}</p><button className="button" onClick={()=>void load()}>Retry</button></div></main>;const t=data?.tracking||{};const activities=t.shipment_track_activities||t.activities||t.timeline||[];const track=Array.isArray(t)?t:activities;const latest=(t.shipment_track&&Array.isArray(t.shipment_track)?t.shipment_track[0]:t.shipment_track)||{};const status=t.status||t.current_status||latest.current_status||latest.status||data?.shipment?.status;const carrier=t.carrier||latest.courier_name||latest.carrier_name;const awb=t.awb||latest.awb_code||data?.shipment?.awb;return <main className="accountPage"><div className="sectionHead"><div><span className="eyebrow">PRIYASA / DELIVERY</span><h1>Track order</h1><p className="muted">Order #{id}</p></div><Link className="textLink" href={`/orders/${encodeURIComponent(id)}`}>← Order details</Link></div><section className="checkoutCard"><div className="orderStatus"><span>Current status</span><strong>{text(status||'Tracking pending')}</strong></div>{carrier&&<p><strong>Carrier:</strong> {carrier}</p>}{awb&&<p><strong>AWB:</strong> {awb}</p>}</section>{track.length?<section className="checkoutCard"><span className="eyebrow">SHIPMENT ACTIVITY</span><div className="timeline">{track.map((a:any,i:number)=><div className={i===0?'done':''} key={String(a.id||a.date||a.activity||i)}><b>{text(a.status||a.activity||a.description||'Shipment update')}</b><span>{a.date||a.datetime||a.timestamp||a.location||''}</span></div>)}</div></section>:<div className="emptyState"><h2>Tracking is not available yet</h2><p>Your order may not have been handed to the carrier. Check again after shipment.</p><button className="textButton" onClick={()=>void load()}>Refresh tracking</button></div>}</main>}
