'use client';
import { useMemo,useState } from 'react'; import { api } from '@/lib/api';
type Variant={id:string|number;size?:string|null;color?:string|null;price?:number;stock?:{available?:number};inventory?:{available?:number;in_stock?:boolean}};
function stockOf(v:Variant|undefined){return v?Number(v.inventory?.available??v.stock?.available??0):0}
export default function ProductActions({variantId,variants=[],sizes=[],colors=[]}:{productId?:string|number;variantId:string|number;variants?:Variant[];sizes?:string[];colors?:string[]}){
 const first=variants[0]; const [size,setSize]=useState(first?.size||sizes[0]||''); const [color,setColor]=useState(first?.color||colors[0]||''); const [quantity,setQuantity]=useState(1); const [busy,setBusy]=useState<'bag'|'wishlist'|null>(null); const [message,setMessage]=useState('');
 const selectedVariant=useMemo(()=>{if(!variants.length)return variantId;return variants.find(v=>(!sizes.length||v.size===size)&&(!colors.length||v.color===color))?.id||''},[variants,variantId,size,color,sizes.length,colors.length]);
 const selected=variants.find(v=>String(v.id)===String(selectedVariant)); const available=selected?stockOf(selected):undefined; const unavailable=variants.length>0&&(!selected||(available??0)<quantity||(available??0)<=0);
 const sizeAvailable=(s:string)=>!variants.length||variants.some(v=>(!colors.length||v.color===color)&&v.size===s&&stockOf(v)>0);
 const colorAvailable=(c:string)=>!variants.length||variants.some(v=>(!sizes.length||v.size===size)&&v.color===c&&stockOf(v)>0);
 async function addToBag(){if(!selectedVariant)return setMessage('Please select an available size and colour.');if(unavailable)return setMessage('Selected variant is out of stock or the requested quantity is unavailable.');setBusy('bag');setMessage('');try{await api('/storefront/cart/items',{method:'POST',body:JSON.stringify({variant_id:selectedVariant,quantity})});setMessage('Added to bag.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to add this item.')}finally{setBusy(null)}}
 async function addToWishlist(){if(!selectedVariant)return setMessage('Please select an available variant.');setBusy('wishlist');setMessage('');try{await api('/storefront/wishlist/toggle',{method:'POST',body:JSON.stringify({variant_id:selectedVariant})});setMessage('Wishlist updated.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to update wishlist.')}finally{setBusy(null)}}
 return <><div className="variantBlock"><strong>Choose your options</strong>{sizes.length?<div><small>Size</small><div className="variantRow">{sizes.map(s=><button type="button" key={s} disabled={!sizeAvailable(s)} aria-disabled={!sizeAvailable(s)} className={size===s?'selected':''} onClick={()=>{setSize(s);setQuantity(1);setMessage('')}}>{s}{!sizeAvailable(s)?' · Out of stock':''}</button>)}</div></div>:null}{colors.length?<div><small>Colour</small><div className="variantRow">{colors.map(c=><button type="button" key={c} disabled={!colorAvailable(c)} aria-disabled={!colorAvailable(c)} className={color===c?'selected':''} onClick={()=>{setColor(c);setQuantity(1);setMessage('')}}>{c}{!colorAvailable(c)?' · Out of stock':''}</button>)}</div></div>:null}{variants.length>0&&!selectedVariant&&<small className="formError">This size/colour combination is unavailable.</small>}</div><div className="variantBlock"><strong>Quantity</strong><div className="qty"><button type="button" aria-label="Decrease quantity" disabled={quantity<=1} onClick={()=>setQuantity(q=>Math.max(1,q-1))}>−</button><span aria-live="polite">{quantity}</span><button type="button" aria-label="Increase quantity" disabled={available===undefined||quantity>=available} onClick={()=>setQuantity(q=>q+1)}>+</button></div>{available!==undefined&&<small className="muted">{available>0?`${available} available`:'Out of stock'}</small>}</div><div className="pdpActions"><button type="button" className="button secondary" disabled={busy!==null||!selectedVariant||unavailable} onClick={addToWishlist}>{busy==='wishlist'?'SAVING…':'♡ WISHLIST'}</button><button type="button" className="button" disabled={busy!==null||!selectedVariant||unavailable} onClick={addToBag}>{busy==='bag'?'ADDING…':'ADD TO BAG'}</button></div><p className="actionMessage" role="status" aria-live="polite">{message}</p></>}
