'use client';

import { useMemo, useState } from 'react';
import { api } from '@/lib/api';

type Variant = { id: string | number; size?: string | null; color?: string | null; price?: number; stock?: { available?: number }; inventory?: { available?: number; in_stock?: boolean } };

export default function ProductActions({ productId, variantId, variants = [], sizes = [], colors = [] }: { productId: string | number; variantId: string | number; variants?: Variant[]; sizes?: string[]; colors?: string[] }) {
  const [size, setSize] = useState(sizes[0] || ''); const [color, setColor] = useState(colors[0] || ''); const [quantity, setQuantity] = useState(1); const [busy, setBusy] = useState<'bag' | 'wishlist' | null>(null); const [message, setMessage] = useState('');
  const selectedVariant = useMemo(() => { if (!variants.length) return variantId; const exact = variants.find(v => (!sizes.length || v.size === size) && (!colors.length || v.color === color)); return exact?.id || variantId; }, [variants, variantId, size, color, sizes.length, colors.length]);
  const selected = variants.find(v => String(v.id) === String(selectedVariant));
  const available = selected ? Number(selected.inventory?.available ?? selected.stock?.available ?? 0) : undefined;
  const unavailable = variants.length > 0 && (!Number.isFinite(available) || Number(available) < quantity);
  async function addToBag() { if (!selectedVariant) return setMessage('This product is currently unavailable.'); if (sizes.length && !size) return setMessage('Please select a size.'); if (colors.length && !color) return setMessage('Please select a colour.'); if (unavailable) return setMessage('Selected quantity is not available.'); setBusy('bag'); setMessage(''); try { await api('/storefront/cart/items', { method: 'POST', body: JSON.stringify({ variant_id: Number(selectedVariant), quantity }) }); setMessage('Added to bag.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to add this item.'); } finally { setBusy(null); } }
  async function addToWishlist() { if (!selectedVariant) return setMessage('This product is currently unavailable.'); setBusy('wishlist'); setMessage(''); try { await api('/storefront/wishlist/items', { method: 'POST', body: JSON.stringify({ product_id: Number(productId), variant_id: Number(selectedVariant) }) }); setMessage('Wishlist updated.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to update wishlist.'); } finally { setBusy(null); } }
  return <><div className="variantBlock"><strong>Choose your options</strong>{sizes.length ? <div><small>Size</small><div className="variantRow">{sizes.map(s => <button type="button" key={s} className={size === s ? 'selected' : ''} onClick={() => { setSize(s); setQuantity(1); }}>{s}</button>)}</div></div> : null}{colors.length ? <div><small>Colour</small><div className="variantRow">{colors.map(c => <button type="button" key={c} className={color === c ? 'selected' : ''} onClick={() => { setColor(c); setQuantity(1); }}>{c}</button>)}</div></div> : null}</div><div className="variantBlock"><strong>Quantity</strong><div className="qty"><button type="button" aria-label="Decrease quantity" disabled={quantity <= 1} onClick={() => setQuantity(q => Math.max(1, q - 1))}>−</button><span aria-live="polite">{quantity}</span><button type="button" aria-label="Increase quantity" disabled={available !== undefined && quantity >= available} onClick={() => setQuantity(q => q + 1)}>+</button></div>{available !== undefined && <small className="muted">{available > 0 ? `${available} available` : 'Out of stock'}</small>}</div><div className="pdpActions"><button type="button" className="button secondary" disabled={busy !== null || !selectedVariant} onClick={addToWishlist}>{busy === 'wishlist' ? 'SAVING…' : '♡ WISHLIST'}</button><button type="button" className="button" disabled={busy !== null || !selectedVariant || unavailable} onClick={addToBag}>{busy === 'bag' ? 'ADDING…' : 'ADD TO BAG'}</button></div><p className="actionMessage" role="status" aria-live="polite">{message}</p></>;
}
