'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, getAccessToken } from '@/lib/api';

type Review={id?:string|number;rating?:number;title?:string;body?:string;comment?:string;review?:string;user_name?:string;customer_name?:string;created_at?:string};
function unwrap(value:any):Review[]{const v=value?.data??value??[];return Array.isArray(v)?v:v.items??v.reviews??v.data??[]}
export default function ProductReviews({productId}:{productId:string|number}){
 const [reviews,setReviews]=useState<Review[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[rating,setRating]=useState(5),[title,setTitle]=useState(''),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[signedIn,setSignedIn]=useState(false);
 async function load(){setLoading(true);try{const r=await api<any>(`/storefront/products/${encodeURIComponent(String(productId))}/reviews`);setReviews(unwrap(r));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load reviews.')}finally{setLoading(false)}}
 useEffect(()=>{setSignedIn(Boolean(getAccessToken()));void load()},[productId]);
 async function submit(){setError('');setMessage('');if(!body.trim()){setError('Write a short review before submitting.');return}setBusy(true);try{await api(`/storefront/products/${encodeURIComponent(String(productId))}/reviews`,{method:'POST',body:JSON.stringify({rating,title:title.trim()||undefined,body:body.trim()})});setTitle('');setBody('');setRating(5);setMessage('Your review was submitted successfully.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to submit review.')}finally{setBusy(false)}}
 return <section className="reviewsSection" aria-labelledby="reviews-title"><div className="sectionHead"><div><span className="eyebrow">PRIYASA / REVIEWS</span><h2 id="reviews-title">Customer reviews</h2></div></div>{signedIn?<div className="reviewComposer"><h3>Share your experience</h3><label>Rating<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value={5}>5 — Excellent</option><option value={4}>4 — Good</option><option value={3}>3 — Average</option><option value={2}>2 — Poor</option><option value={1}>1 — Very poor</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="What stood out?"/></label><label>Review<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} rows={4} placeholder="Tell other shoppers about the product."/></label>{error&&<div className="formError" role="alert">{error}</div>}{message&&<div className="formMessage" role="status">{message}</div>}<button className="button" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit review'}</button></div>:<p className="muted"><Link href={`/auth/login?next=${encodeURIComponent(`/product/${String(productId)}`)}`}>Sign in</Link> to write a review.</p>}{loading?<p className="muted">Loading reviews…</p>:error&&!signedIn?<p className="muted">Reviews are temporarily unavailable.</p>:reviews.length===0?<p className="muted">No reviews yet. Be the first to share your experience after purchase.</p>:<div className="reviewList">{reviews.map((review,index)=><article className="reviewCard" key={review.id??index}><div className="reviewMeta"><strong>★ {Number(review.rating||0).toFixed(1)}</strong><span>{review.customer_name||review.user_name||'Verified customer'}</span></div>{review.title&&<h3>{review.title}</h3>}<p>{review.body||review.comment||review.review||''}</p>{review.created_at&&<small className="muted">{new Date(review.created_at).toLocaleDateString('en-IN')}</small>}</article>)}</div>}</section>
}
